### ISSUE TITLE
Warning from esbuild

### ISSUE THREAD

**Issue by mdarocha** [Olian04/typescript-helpers#4]
Hi,

I've got this module installed as a transient dependency, and when using esbuild to compile the project, I'm getting the following warning:

```
▲ [WARNING] "dist/api.d.ts" is not a valid value for the "type" field

    node_modules/@olian/typescript-helpers/package.json:6:10:
      6 │   "type": "dist/api.d.ts",
        ╵           ~~~~~~~~~~~~~~~

  The "type" field must be set to either "commonjs" or "module".
```

It seems that according to the [NodeJS documentation](https://nodejs.org/api/packages.html#type), the `type` field is currently incorrectly set.

**Comment by Olian04** [comment]
Thank you for pointing it out!
This should now be fixed in the latest release, version [2.3.1](https://www.npmjs.com/package/@olian/typescript-helpers/v/2.3.1).
